export type User = {
  memberId?: number,
  nickName?: string,
  mobilePhone?: string,
  area?: number,
  district?: number,
  chain?: number,
  store?: string,
  gender?: number,
  headimg? :string,
  orgNo? : string,
  roles? : Array<number>,
  memberName? : string,
  orgName?:string,
  status?: number,
  orgStatus?: number,
  orgId?: string,
}
